---
    environment: production
    chdir: /srv/ruby/irclogger
    address: 127.0.0.1
    user: root
    group: root
    port: 10000
    pid: /srv/ruby/irclogger/thin.pid
    rackup: /srv/ruby/irclogger/config.ru
    log: /srv/ruby/irclogger/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true 
